# Capstone Project - The Battle of Neighborhoods (Week 1)

## Data <a name="data"></a>

The following data sets will be generated to provide insights on our proposed business problem:

* Latitude and Longitude values of Downtown Toronto using geopy library
* Search and Query of number of restaurant and their categories with locations, using Foursquare API
* Restaurant Rating, Price, Tier and Currency by making calls to Foursquare API
* Map of the downtown area, using folium plotting library
* Using basic google map search to visualize approximate cordinate of Downtown Toronto

Factor that will influence our analysis:

* Selection of existing restaurants in any category
* Distance of restaurants in the neighborhood
* Approximate defined center, which is the downtown area
* The Price, Rating and Tier for comparison

#### Import necessary Libraries

In [ ]:
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

# To simplify, output was cleared

#### Define Foursquare Credentials and Version

In [2]:
CLIENT_ID = '2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH' # your Foursquare ID
CLIENT_SECRET = 'FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 10
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH
CLIENT_SECRET:FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS

In [3]:
# Use geopy library to get the latitude and longitude values of Downtown Toronto

address = 'Downtown Toronto, ON'
geolocator = Nominatim(user_agent="Downtown_Toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Downtown Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Downtown Toronto are 43.6563221, -79.3809161.

#### Search for a specific venue category

In [4]:
# define a query to search for Restaurant within 500 metres from Downtown Toronto

search_query = 'Restaurant'
radius = 500
print(search_query + ' .... OK!')

Restaurant .... OK!

#### Define the corresponding URL and limit = 10

In [5]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH&client_secret=FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS&ll=43.6563221,-79.3809161&v=20180604&query=Restaurant&radius=500&limit=10'

#### Make the call to foursquare api; send GET Request and examine results

In [ ]:
results = requests.get(url).json()
results

# To simplify, output was cleared

#### Get relevant part of JSON and transform it into a *pandas* dataframe

In [7]:
# assign relevant part of JSON to venues
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,id,name,categories,referralId,hasPerk,location.address,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress,location.crossStreet,venuePage.id
0,4ad4c05ff964a52048f720e3,Hemispheres Restaurant & Bistro,"[{'id': '4bf58dd8d48988d14e941735', 'name': 'A...",v-1575952267,False,110 Chestnut Street,43.654884,-79.385931,"[{'label': 'display', 'lat': 43.65488413420439...",434,M5G 1R3,CA,Toronto,ON,Canada,"[110 Chestnut Street, Toronto ON M5G 1R3, Canada]",NaN,NaN
1,4b295e10f964a520ba9d24e3,Richtree Natural Market Restaurants,"[{'id': '4bf58dd8d48988d1c4941735', 'name': 'R...",v-1575952267,False,14 Queen St W,43.652614,-79.380231,"[{'label': 'display', 'lat': 43.65261436174172...",416,M5H 3X4,CA,Toronto,ON,Canada,"[14 Queen St W, Toronto ON M5H 3X4, Canada]",NaN,NaN
2,4edbccaaf9abeea3db5268df,Terrace Restaurant at Elmwood,"[{'id': '4bf58dd8d48988d14e941735', 'name': 'A...",v-1575952267,False,NaN,43.656101,-79.381480,"[{'label': 'display', 'lat': 43.65610066909799...",51,NaN,CA,NaN,NaN,Canada,[Canada],NaN,NaN
3,4fbbb3ace4b01e39077b4d55,Akashiro Japanese Restaurant & Bar,"[{'id': '4bf58dd8d48988d1d2941735', 'name': 'S...",v-1575952267,False,220 Yonge St.,43.655965,-79.380541,"[{'label': 'display', 'lat': 43.65596504293232...",49,NaN,CA,Toronto,ON,Canada,[220 Yonge St. (in Toronto Eaton Centre Urban ...,in Toronto Eaton Centre Urban Eatery,NaN
4,4ad7929cf964a520500c21e3,The Senator Restaurant,"[{'id': '4bf58dd8d48988d147941735', 'name': 'D...",v-1575952267,False,249 Victoria Street,43.655641,-79.379199,"[{'label': 'display', 'lat': 43.65564091455335...",157,M5B 1T8,CA,Toronto,ON,Canada,[249 Victoria Street (btwn Dundas St E and Shu...,btwn Dundas St E and Shuter St,55585058

#### Define information of interest and filter dataframe

In [8]:
# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

,name,categories,address,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,crossStreet,id
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,"[{'label': 'display', 'lat': 43.65488413420439...",434,M5G 1R3,CA,Toronto,ON,Canada,"[110 Chestnut Street, Toronto ON M5G 1R3, Canada]",NaN,4ad4c05ff964a52048f720e3
1,Richtree Natural Market Restaurants,Restaurant,14 Queen St W,43.652614,-79.380231,"[{'label': 'display', 'lat': 43.65261436174172...",416,M5H 3X4,CA,Toronto,ON,Canada,"[14 Queen St W, Toronto ON M5H 3X4, Canada]",NaN,4b295e10f964a520ba9d24e3
2,Terrace Restaurant at Elmwood,American Restaurant,NaN,43.656101,-79.381480,"[{'label': 'display', 'lat': 43.65610066909799...",51,NaN,CA,NaN,NaN,Canada,[Canada],NaN,4edbccaaf9abeea3db5268df
3,Akashiro Japanese Restaurant & Bar,Sushi Restaurant,220 Yonge St.,43.655965,-79.380541,"[{'label': 'display', 'lat': 43.65596504293232...",49,NaN,CA,Toronto,ON,Canada,[220 Yonge St. (in Toronto Eaton Centre Urban ...,in Toronto Eaton Centre Urban Eatery,4fbbb3ace4b01e39077b4d55
4,The Senator Restaurant,Diner,249 Victoria Street,43.655641,-79.379199,"[{'label': 'display', 'lat': 43.65564091455335...",157,M5B 1T8,CA,Toronto,ON,Canada,[249 Victoria Street (btwn Dundas St E and Shu...,btwn Dundas St E and Shuter St,4ad7929cf964a520500c21e3
5,Subway,Sandwich Place,10 Dundas St. E,43.656260,-79.380920,"[{'label': 'display', 'lat': 43.65625998968890...",6,M5B 2G9,CA,Toronto,ON,Canada,"[10 Dundas St. E (at Yonge St.), Toronto ON M5...",at Yonge St.,4c6abb8c2c29d13ad2720e41
6,Adega Restaurant,Restaurant,33 Elm St,43.657519,-79.383462,"[{'label': 'display', 'lat': 43.65751886446546...",244,M5G 1H1,CA,Toronto,ON,Canada,"[33 Elm St (at Bay St), Toronto ON M5G 1H1, Ca...",at Bay St,4ad4c060f964a52070f720e3
7,Hong Shing Chinese Restaurant,Chinese Restaurant,195 Dundas St W,43.654925,-79.387089,"[{'label': 'display', 'lat': 43.65492521335936...",520,M5G 1C7,CA,Toronto,ON,Canada,"[195 Dundas St W (at University Ave), Toronto ...",at University Ave,4b2027b5f964a520f82d24e3
8,Kyoto House Japanese Restaurant,Sushi Restaurant,143 Dundas St. West,43.655381,-79.385270,"[{'label': 'display', 'lat': 43.65538110598594...",365,NaN,CA,Toronto,ON,Canada,"[143 Dundas St. West, Toronto ON, Canada]",NaN,4ae4b055f964a520229d21e3
9,Yueh Tung Chinese Restaurant,Chinese Restaurant,126 Elizabeth St.,43.655281,-79.385337,"[{'label': 'display', 'lat': 43.65528126342919...",374,NaN,CA,Toronto,ON,Canada,"[126 Elizabeth St. (Dundas St.), Toronto ON, C...",Dundas St.,52a7ae41498eed3af4d0a3fa

In [9]:
dataframe_filtered.name

0        Hemispheres Restaurant & Bistro
1    Richtree Natural Market Restaurants
2          Terrace Restaurant at Elmwood
3     Akashiro Japanese Restaurant & Bar
4                 The Senator Restaurant
5                                 Subway
6                       Adega Restaurant
7          Hong Shing Chinese Restaurant
8        Kyoto House Japanese Restaurant
9           Yueh Tung Chinese Restaurant
Name: name, dtype: object

#### Generate map of the city’s downtown area

In [10]:
# Let’s locate the approximate center and explore neighboring restaurants
# Zoom in to visualize
# Note: Github may not display map

venues_map = folium.Map(location=[latitude, longitude], zoom_start=10) # generate map centred around 

# add a red circle marker to represent 
folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='Downtown Toronto',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the restaurants as blue circle markers
for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

##### Approximate Defined Center: Google Maps

In [11]:
# We searched cordinate 43.6563221, -79.3809161 for Downtown Toronto
# Result shows "418 The PATH - Yonge-Dundas Square, Toronto, ON M5B 1R4, Canada"
# Represented by a red circle marker from the generated map above

#### Dataframe Clean Up

In [12]:
# Let's sort by distance
sort_by_distance = dataframe_filtered.sort_values('distance')
sort_by_distance

,name,categories,address,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,crossStreet,id
5,Subway,Sandwich Place,10 Dundas St. E,43.656260,-79.380920,"[{'label': 'display', 'lat': 43.65625998968890...",6,M5B 2G9,CA,Toronto,ON,Canada,"[10 Dundas St. E (at Yonge St.), Toronto ON M5...",at Yonge St.,4c6abb8c2c29d13ad2720e41
3,Akashiro Japanese Restaurant & Bar,Sushi Restaurant,220 Yonge St.,43.655965,-79.380541,"[{'label': 'display', 'lat': 43.65596504293232...",49,NaN,CA,Toronto,ON,Canada,[220 Yonge St. (in Toronto Eaton Centre Urban ...,in Toronto Eaton Centre Urban Eatery,4fbbb3ace4b01e39077b4d55
2,Terrace Restaurant at Elmwood,American Restaurant,NaN,43.656101,-79.381480,"[{'label': 'display', 'lat': 43.65610066909799...",51,NaN,CA,NaN,NaN,Canada,[Canada],NaN,4edbccaaf9abeea3db5268df
4,The Senator Restaurant,Diner,249 Victoria Street,43.655641,-79.379199,"[{'label': 'display', 'lat': 43.65564091455335...",157,M5B 1T8,CA,Toronto,ON,Canada,[249 Victoria Street (btwn Dundas St E and Shu...,btwn Dundas St E and Shuter St,4ad7929cf964a520500c21e3
6,Adega Restaurant,Restaurant,33 Elm St,43.657519,-79.383462,"[{'label': 'display', 'lat': 43.65751886446546...",244,M5G 1H1,CA,Toronto,ON,Canada,"[33 Elm St (at Bay St), Toronto ON M5G 1H1, Ca...",at Bay St,4ad4c060f964a52070f720e3
8,Kyoto House Japanese Restaurant,Sushi Restaurant,143 Dundas St. West,43.655381,-79.385270,"[{'label': 'display', 'lat': 43.65538110598594...",365,NaN,CA,Toronto,ON,Canada,"[143 Dundas St. West, Toronto ON, Canada]",NaN,4ae4b055f964a520229d21e3
9,Yueh Tung Chinese Restaurant,Chinese Restaurant,126 Elizabeth St.,43.655281,-79.385337,"[{'label': 'display', 'lat': 43.65528126342919...",374,NaN,CA,Toronto,ON,Canada,"[126 Elizabeth St. (Dundas St.), Toronto ON, C...",Dundas St.,52a7ae41498eed3af4d0a3fa
1,Richtree Natural Market Restaurants,Restaurant,14 Queen St W,43.652614,-79.380231,"[{'label': 'display', 'lat': 43.65261436174172...",416,M5H 3X4,CA,Toronto,ON,Canada,"[14 Queen St W, Toronto ON M5H 3X4, Canada]",NaN,4b295e10f964a520ba9d24e3
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,"[{'label': 'display', 'lat': 43.65488413420439...",434,M5G 1R3,CA,Toronto,ON,Canada,"[110 Chestnut Street, Toronto ON M5G 1R3, Canada]",NaN,4ad4c05ff964a52048f720e3
7,Hong Shing Chinese Restaurant,Chinese Restaurant,195 Dundas St W,43.654925,-79.387089,"[{'label': 'display', 'lat': 43.65492521335936...",520,M5G 1C7,CA,Toronto,ON,Canada,"[195 Dundas St W (at University Ave), Toronto ...",at University Ave,4b2027b5f964a520f82d24e3

In [13]:
# Hide the index
sort_by_distance.style.hide_index()

#### Explore Restaurants using their ID

In [14]:
# Making calls to Foursquare API to get 'given values'
# The Senator Restaurant would be our pilot call
# We then get the Rating, Price, Tier and Currency for others

In [15]:
venue_id = '4ad7929cf964a520500c21e3' # ID of The Senator Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)
url

'https://api.foursquare.com/v2/venues/4ad7929cf964a520500c21e3?client_id=2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH&client_secret=FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS&v=20180604'

In [ ]:
result = requests.get(url).json()
print(result['response']['venue'].keys())
result['response']['venue']

# To simplify, output was cleared

In [17]:
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

7.9

In [18]:
try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')

{'tier': 2, 'message': 'Moderate', 'currency': '$'}

In [19]:
# Now we leverage the Foursquare location data to the fullest
# let's get the Rating, Price, Tier and Currency for other restaurants


venue_id = '4c6abb8c2c29d13ad2720e41' # Subway
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.') 
    
    
venue_id = '4fbbb3ace4b01e39077b4d55' # Akashiro Japanese Restaurant & Bar
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.') 
    
        
venue_id = '4edbccaaf9abeea3db5268df' # Terrace Restaurant at Elmwood
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    
    
venue_id = '539c6f13498e06f4cc765165' # The Elm Tree Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    
    
venue_id = '5a8b24b2018cbb6c4ca70dae' # Hendricks Restaurant & Bar
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    

venue_id = '4ae4b055f964a520229d21e3' # Kyoto House Japanese Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    

venue_id = '52a7ae41498eed3af4d0a3fa' # Yueh Tung Chinese Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')

venue_id = '4b295e10f964a520ba9d24e3' # Richtree Natural Market Restaurants
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')


venue_id = '4ad4c05ff964a52048f720e' # Hemispheres Restaurant & Bistro
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')

5.7
{'tier': 1, 'message': 'Cheap', 'currency': '$'}
5.4
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
This venue has not been rated yet.
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
8.3
No Details.
6.1
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
5.9
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
7.8
{'tier': 1, 'message': 'Cheap', 'currency': '$'}
6.2
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
This venue has not been rated yet.
No Details.

##### Dataset Results above were extracted to csv format

In [20]:
# Let's get the csv file to create new dataframe
df_dtres = pd.read_csv('DT_Res.csv')
df_dtres

                            Restaurant Rating      Price Tier
0                               Subway     5.7     Cheap     1
1   Akashiro Japanese Restaurant & Bar     5.4  Moderate     2
2        Terrace Restaurant at Elmwood      NR  Moderate     2
3               The Senator Restaurant     7.9  Moderate     2
4              The Elm Tree Restaurant     8.3        ND    ND
5           Hendricks Restaurant & Bar     6.1  Moderate     2
6      Kyoto House Japanese Restaurant     5.9  Moderate     2
7         Yueh Tung Chinese Restaurant     7.8     Cheap     1
8  Richtree Natural Market Restaurants     6.2  Moderate     2
9      Hemispheres Restaurant & Bistro      NR        ND    ND

##### New Dataframe: Price and Rating

In [21]:
# Look for word 'Cheap'
df_word=df_dtres[df_dtres['Price'].str.contains('Cheap')].reset_index(drop=True)

# Hide the index
df_word.style.hide_index()

In [22]:
# Look for word 'Moderate'
df_word=df_dtres[df_dtres['Price'].str.contains('Moderate')].reset_index(drop=True)

# Hide the index
df_word.style.hide_index()

##### Top picks by Price and Rating: Yueh Tung Chinese Restaurant and The Senator Restaurant

#### Final Deliverables

In Week 2, we will cover:
* Components: Methodology, Analysis, Results and Discussion, Conclusion
* Full Report with Components and Presentation